// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Feb 18 14:55:33 2007

#include "aboutDlg.h"
#include <res/xpm_sparklogo.xpm>

aboutDlg::aboutDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long /*style*/):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: aboutDlg::aboutDlg
    mBitmap = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap);
    label_1 = new wxStaticText(this, wxID_ANY, wxT("SimSpark Copyright (C) RoboCup Soccer Server 3D Maintenance Group"));
    button_1 = new wxButton(this, wxID_OK, wxT("&Ok"));

    set_properties();
    do_layout();
    // end wxGlade

    mBitmap->SetBitmap(wxBitmap(xpm_sparklogo));
    Layout();
}

void aboutDlg::set_properties()
{
    // begin wxGlade: aboutDlg::set_properties
    SetTitle(wxT("About"));
    mBitmap->SetMinSize(wxSize(500, 200));
    // end wxGlade
}


void aboutDlg::do_layout()
{
    // begin wxGlade: aboutDlg::do_layout
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxVERTICAL);
    sizer_9->Add(mBitmap, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 5);
    sizer_9->Add(label_1, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 5);
    sizer_9->Add(button_1, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 5);
    SetSizer(sizer_9);
    sizer_9->Fit(this);
    Layout();
    // end wxGlade
}

