#define GUI_LAYOUT_DIRECTORY "${GUI_LAYOUT_DIR}"

#define GUI_PLUGIN_DIRECTORY_1 "${GUI_PLUGIN_DIR_1}"

#define GUI_PLUGIN_DIRECTORY_2 "${GUI_PLUGIN_DIR_2}"

#define GUI_SETUP_DIRECTORY "${GUI_SETUP_DIR}"

#define SCRIPT_INCLUDE_DIRECTORY_1 "${SCRIPT_INCLUDE_DIR_1}"

#define SCRIPT_INCLUDE_DIRECTORY_2 "${SCRIPT_INCLUDE_DIR_2}"

#define EXECUTABLE_INCLUDE_DIRECTORY "${EXECUTABLE_INCLUDE_DIR}"


